name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      # If you don't have a package.json or dependencies, you can remove this step

    - name: Build site
      run: npm run build
      # If you don't have a build step, you can remove this step

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Change if your built site is in a different directory, e.g., ./dist or ./build
        # If you have a build directory, set publish_dir accordingly

    - name: Clean up
      run: rm -rf node_modules
